server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml              #mybatis配置文件所在路径
  type-aliases-package: com.zkj.springcloud.entities              #所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                           #mapper映射文件

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                  #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver                    #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-idle: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept8002
    prefer-ip-address: true

info:
  app.name: zkj-microservicecloud
  company.name: www.baidu.com
  build.artfactId: $project.artifactId$
  build.version: $project.version$